/** otp_mapping.h */
/**
 * Copyright 2019 SiFive
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
*/
#ifndef _OTP_MAPPING_H_
#define _OTP_MAPPING_H_

/** Global includes */
#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
#include <common.h>
/** Other includes */
/** Local includes */

/** External declarations */
/** Local declarations */

/** Defines *******************************************************************/
#define	C_OTP_MAPPING_BASE_OFFSET				0

#define	C_OTP_BASIC_ELMNT_SIZE					sizeof(uint32_t)

/** All parameters size are in Bytes */

/** UID - 0x000 ***************************************************************/
#define	C_OTP_MAPPING_UID_OFST					C_OTP_MAPPING_BASE_OFFSET
#define	C_OTP_MAPPING_UID_SIZE					C_UID_SIZE_IN_BYTES
#define	C_OTP_MAPPING_UID_END_OFST				( C_OTP_MAPPING_UID_OFST + C_OTP_MAPPING_UID_SIZE )

/** TM_LOCK - 0x0010 **********************************************************/
#define	C_OTP_MAPPING_TM_LOCK_OFST				C_OTP_MAPPING_UID_END_OFST
#define	C_OTP_MAPPING_TM_LOCK_SIZE				C_OTP_BASIC_ELMNT_SIZE
#define	C_OTP_MAPPING_TM_LOCK_END_OFST			( C_OTP_MAPPING_TM_LOCK_OFST + C_OTP_MAPPING_TM_LOCK_SIZE )

/** PSD_LOCK - 0x0014 *********************************************************/
#define	C_OTP_MAPPING_PSD_LOCK_OFST				C_OTP_MAPPING_TM_LOCK_END_OFST
#define	C_OTP_MAPPING_PSD_LOCK_SIZE				C_OTP_BASIC_ELMNT_SIZE
#define	C_OTP_MAPPING_PSD_LOCK_END_OFST			( C_OTP_MAPPING_PSD_LOCK_OFST + C_OTP_MAPPING_PSD_LOCK_SIZE )

/** RMA_MODE - 0x0018 *********************************************************/
#define	C_OTP_MAPPING_RMA_MODE_OFST				C_OTP_MAPPING_PSD_LOCK_END_OFST
#define	C_OTP_MAPPING_RMA_MODE_SIZE				C_OTP_BASIC_ELMNT_SIZE
#define	C_OTP_MAPPING_RMA_MODE_END_OFST			( C_OTP_MAPPING_RMA_MODE_OFST + C_OTP_MAPPING_RMA_MODE_SIZE )

/** RFU0 - 0x001c *************************************************************/
#define	C_OTP_MAPPING_RFU0_OFST					C_OTP_MAPPING_RMA_MODE_END_OFST
#define	C_OTP_MAPPING_RFU0_SIZE					C_OTP_BASIC_ELMNT_SIZE
#define	C_OTP_MAPPING_RFU0_END_OFST				( C_OTP_MAPPING_RFU0_OFST + C_OTP_MAPPING_RFU0_SIZE )

/** PHASE#1 Pattern - 0x0020 **************************************************/
#define	C_OTP_MAPPING_PHASE_OFFSET				C_OTP_MAPPING_RFU0_END_OFST
#define	C_OTP_MAPPING_PHASE_ELMT_SIZE			( 2 * C_OTP_BASIC_ELMNT_SIZE )

#define	C_OTP_MAPPING_PHASE1_OFST				C_OTP_MAPPING_RFU0_END_OFST
#define	C_OTP_MAPPING_PHASE1_SIZE				C_OTP_MAPPING_PHASE_ELMT_SIZE
#define	C_OTP_MAPPING_PHASE1_END_OFST			( C_OTP_MAPPING_PHASE1_OFST + C_OTP_MAPPING_PHASE1_SIZE )
/** PHASE#2_1 Pattern - 0x0028 */
#define	C_OTP_MAPPING_PHASE2_1_OFST				C_OTP_MAPPING_PHASE1_END_OFST
#define	C_OTP_MAPPING_PHASE2_1_SIZE				C_OTP_MAPPING_PHASE_ELMT_SIZE
#define	C_OTP_MAPPING_PHASE2_1_END_OFST			( C_OTP_MAPPING_PHASE2_1_OFST + C_OTP_MAPPING_PHASE2_1_SIZE )
/** PHASE#2_2 Pattern - 0x0030 */
#define	C_OTP_MAPPING_PHASE2_2_OFST				C_OTP_MAPPING_PHASE2_1_END_OFST
#define	C_OTP_MAPPING_PHASE2_2_SIZE				C_OTP_MAPPING_PHASE_ELMT_SIZE
#define	C_OTP_MAPPING_PHASE2_2_END_OFST			( C_OTP_MAPPING_PHASE2_2_OFST + C_OTP_MAPPING_PHASE2_2_SIZE )

#define	C_OTP_MAPPING_PHASE_SIZE				( C_OTP_MAPPING_PHASE1_SIZE + C_OTP_MAPPING_PHASE2_1_SIZE + C_OTP_MAPPING_PHASE2_2_SIZE )
#define	C_OTP_MAPPING_PHASE_END_OFST			( C_OTP_MAPPING_PHASE_OFFSET + C_OTP_MAPPING_PHASE_SIZE )

/** UART configuration parameters - slot1 - 0x0038 ****************************/
#define	C_OTP_MAPPING_UART_AREA_OFST			C_OTP_MAPPING_PHASE_END_OFST
#define	C_OTP_MAPPING_UART_ELMNT_SIZE			sizeof(uint32_t)

#define	C_OTP_MAPPING_UART_CFG0_OFST			C_OTP_MAPPING_UART_AREA_OFST
#define	C_OTP_MAPPING_UART_CFG0_SIZE			C_OTP_MAPPING_UART_ELMNT_SIZE
#define	C_OTP_MAPPING_UART_CFG0_END_OFST		( C_OTP_MAPPING_UART_CFG0_OFST + C_OTP_MAPPING_UART_CFG0_SIZE )
/** UART configuration parameters - slot2 - 0x003c */
#define	C_OTP_MAPPING_UART_CFG1_OFST			C_OTP_MAPPING_UART_CFG0_END_OFST
#define	C_OTP_MAPPING_UART_CFG1_SIZE			C_OTP_MAPPING_UART_ELMNT_SIZE
#define	C_OTP_MAPPING_UART_CFG1_END_OFST		( C_OTP_MAPPING_UART_CFG1_OFST + C_OTP_MAPPING_UART_CFG1_SIZE )
/** UART configuration parameters - slot3 - 0x0040 */
#define	C_OTP_MAPPING_UART_CFG2_OFST			C_OTP_MAPPING_UART_CFG1_END_OFST
#define	C_OTP_MAPPING_UART_CFG2_SIZE			C_OTP_MAPPING_UART_ELMNT_SIZE
#define	C_OTP_MAPPING_UART_CFG2_END_OFST		( C_OTP_MAPPING_UART_CFG2_OFST + C_OTP_MAPPING_UART_CFG2_SIZE )

#define	C_OTP_MAPPING_UART_TOTAL_SIZE			( C_OTP_MAPPING_UART_CFG0_SIZE + C_OTP_MAPPING_UART_CFG1_SIZE + C_OTP_MAPPING_UART_CFG2_SIZE )
#define	C_OTP_MAPPING_UART_END_OFST				( C_OTP_MAPPING_UART_AREA_OFST + C_OTP_MAPPING_UART_TOTAL_SIZE )

#define	C_OTP_MAPPING_LAST_UART_OFST			( C_OTP_MAPPING_UART_END_OFST - C_OTP_MAPPING_UART_ELMNT_SIZE )
#define C_OTP_MAPPING_NB_UART_SLOTS				( ( C_OTP_MAPPING_UART_END_OFST - C_OTP_MAPPING_UART_AREA_OFST ) / C_OTP_MAPPING_UART_ELMNT_SIZE )

#define C_OTP_MAPPING_UART_SLOT_MAX				( C_OTP_MAPPING_NB_UART_SLOTS - 1 )

/** RFU1 - 0x0044 *************************************************************/
#define	C_OTP_MAPPING_RFU1_OFST					C_OTP_MAPPING_UART_END_OFST
#define	C_OTP_MAPPING_RFU1_SIZE					( 3 * C_OTP_BASIC_ELMNT_SIZE )
#define	C_OTP_MAPPING_RFU1_END_OFST				( C_OTP_MAPPING_RFU1_OFST + C_OTP_MAPPING_RFU1_SIZE )

/** SUP Stimulus **************************************************************/
#define	C_OTP_MAPPING_SUP_STIM_AREA_OFST		C_OTP_MAPPING_RFU1_END_OFST
#define	C_OTP_MAPPING_SUP_STIM_ELMNT_SIZE		sizeof(uint32_t)

#define	C_OTP_MAPPING_SUP_STIM1_OFST			C_OTP_MAPPING_SUP_STIM_AREA_OFST
#define	C_OTP_MAPPING_SUP_STIM1_SIZE			C_OTP_MAPPING_SUP_STIM_ELMNT_SIZE
#define	C_OTP_MAPPING_SUP_STIM1_END_OFST		( C_OTP_MAPPING_SUP_STIM1_OFST + C_OTP_MAPPING_SUP_STIM1_SIZE )

#define	C_OTP_MAPPING_SUP_STIM2_OFST			C_OTP_MAPPING_SUP_STIM1_END_OFST
#define	C_OTP_MAPPING_SUP_STIM2_SIZE			C_OTP_MAPPING_SUP_STIM_ELMNT_SIZE
#define	C_OTP_MAPPING_SUP_STIM2_END_OFST		( C_OTP_MAPPING_SUP_STIM2_OFST + C_OTP_MAPPING_SUP_STIM2_SIZE )

#define	C_OTP_MAPPING_SUP_STIM3_OFST			C_OTP_MAPPING_SUP_STIM2_END_OFST
#define	C_OTP_MAPPING_SUP_STIM3_SIZE			C_OTP_MAPPING_SUP_STIM_ELMNT_SIZE
#define	C_OTP_MAPPING_SUP_STIM3_END_OFST		( C_OTP_MAPPING_SUP_STIM3_OFST + C_OTP_MAPPING_SUP_STIM3_SIZE )

#define	C_OTP_MAPPING_SUP_STIM_END_OFST			C_OTP_MAPPING_SUP_STIM3_END_OFST

#define	C_OTP_MAPPING_LAST_SUP_STIM_OFST		( C_OTP_MAPPING_SUP_STIM_END_OFST - C_OTP_MAPPING_SUP_STIM_ELMNT_SIZE )
#define C_OTP_MAPPING_NB_SUP_STIM_SLOTS			( ( C_OTP_MAPPING_SUP_STIM_END_OFST - C_OTP_MAPPING_SUP_STIM_AREA_OFST ) / C_OTP_MAPPING_SUP_STIM_ELMNT_SIZE )

#define C_OTP_MAPPING_SUP_STIM_SLOT_MAX			( C_OTP_MAPPING_NB_SUP_STIM_SLOTS - 1 )

/** CUK ***********************************************************************/
#define	C_OTP_MAPPING_CUK_DESC_OFST				C_OTP_MAPPING_SUP_STIM_END_OFST
#define	C_OTP_MAPPING_CUK_DESC_SIZE				C_OTP_BASIC_ELMNT_SIZE
#define	C_OTP_MAPPING_CUK_DESC_END_OFST			( C_OTP_MAPPING_CUK_DESC_OFST + C_OTP_MAPPING_CUK_DESC_SIZE )

#define	C_OTP_MAPPING_CUK_OFST					C_OTP_MAPPING_CUK_DESC_END_OFST
#define	C_OTP_MAPPING_CUK_SIZE					( 2 * C_EDCSA384_SIZE )
#define	C_OTP_MAPPING_CUK_END_OFST				( C_OTP_MAPPING_CUK_OFST + C_OTP_MAPPING_CUK_SIZE )

/** CSK ***********************************************************************/
#define	C_OTP_MAPPING_CSK_OFST					C_OTP_MAPPING_CUK_END_OFST
#define	C_OTP_MAPPING_CSK_DESC_ELMT_SIZE		C_OTP_BASIC_ELMNT_SIZE
#define	C_OTP_MAPPING_CSK_KEY_SIZE				( 2 * C_EDCSA384_SIZE )

#define	C_OTP_MAPPING_CSK_AERA_SIZE				( C_OTP_MAPPING_CSK_DESC_ELMT_SIZE +\
													( 2 * C_OTP_MAPPING_CSK_KEY_SIZE ) )

/** CSK descriptor - slot1 - 0x00b4 *******************************************/
#define	C_OTP_MAPPING_CSK1_DESC_OFST			C_OTP_MAPPING_CSK_OFST
#define	C_OTP_MAPPING_CSK1_DESC_SIZE			C_OTP_MAPPING_CSK_DESC_ELMT_SIZE
#define	C_OTP_MAPPING_CSK1_DESC_END_OFST		( C_OTP_MAPPING_CSK1_DESC_OFST + C_OTP_MAPPING_CSK1_DESC_SIZE )
/** CSK - slot1 - 0x00b8 */
#define	C_OTP_MAPPING_CSK1_KEY_OFST				C_OTP_MAPPING_CSK1_DESC_END_OFST
#define	C_OTP_MAPPING_CSK1_KEY_SIZE				C_OTP_MAPPING_CSK_KEY_SIZE
#define	C_OTP_MAPPING_CSK1_KEY_END_OFST			( C_OTP_MAPPING_CSK1_KEY_OFST + C_OTP_MAPPING_CSK1_KEY_SIZE )
/** CSK Signature - slot1 - 0x0118 */
#define	C_OTP_MAPPING_CSK1_SIGN_OFST			C_OTP_MAPPING_CSK1_KEY_END_OFST
#define	C_OTP_MAPPING_CSK1_SIGN_SIZE			C_OTP_MAPPING_CSK_KEY_SIZE
#define	C_OTP_MAPPING_CSK1_SIGN_END_OFST		( C_OTP_MAPPING_CSK1_SIGN_OFST + C_OTP_MAPPING_CSK1_SIGN_SIZE )

/** CSK descriptor - slot2 - 0x0114 *******************************************/
#define	C_OTP_MAPPING_CSK2_DESC_OFST			C_OTP_MAPPING_CSK1_SIGN_END_OFST
#define	C_OTP_MAPPING_CSK2_DESC_SIZE			C_OTP_MAPPING_CSK_DESC_ELMT_SIZE
#define	C_OTP_MAPPING_CSK2_DESC_END_OFST		( C_OTP_MAPPING_CSK2_DESC_OFST + C_OTP_MAPPING_CSK2_DESC_SIZE )
/** CSK - slot2 - 0x0118 */
#define	C_OTP_MAPPING_CSK2_KEY_OFST				C_OTP_MAPPING_CSK2_DESC_END_OFST
#define	C_OTP_MAPPING_CSK2_KEY_SIZE				C_OTP_MAPPING_CSK_KEY_SIZE
#define	C_OTP_MAPPING_CSK2_KEY_END_OFST			( C_OTP_MAPPING_CSK2_KEY_OFST + C_OTP_MAPPING_CSK2_KEY_SIZE )
/** CSK Signature - slot2 - 0x0178 */
#define	C_OTP_MAPPING_CSK2_SIGN_OFST			C_OTP_MAPPING_CSK2_KEY_END_OFST
#define	C_OTP_MAPPING_CSK2_SIGN_SIZE			C_OTP_MAPPING_CSK_KEY_SIZE
#define	C_OTP_MAPPING_CSK2_SIGN_END_OFST		( C_OTP_MAPPING_CSK2_SIGN_OFST + C_OTP_MAPPING_CSK2_SIGN_SIZE )

/** CSK descriptor - slot3 - 0x01d8 *******************************************/
#define	C_OTP_MAPPING_CSK3_DESC_OFST			C_OTP_MAPPING_CSK2_SIGN_END_OFST
#define	C_OTP_MAPPING_CSK3_DESC_SIZE			C_OTP_MAPPING_CSK_DESC_ELMT_SIZE
#define	C_OTP_MAPPING_CSK3_DESC_END_OFST		( C_OTP_MAPPING_CSK3_DESC_OFST + C_OTP_MAPPING_CSK3_DESC_SIZE )
/** CSK - slot3 - 0x01dc */
#define	C_OTP_MAPPING_CSK3_KEY_OFST				C_OTP_MAPPING_CSK3_DESC_END_OFST
#define	C_OTP_MAPPING_CSK3_KEY_SIZE				C_OTP_MAPPING_CSK_KEY_SIZE
#define	C_OTP_MAPPING_CSK3_KEY_END_OFST			( C_OTP_MAPPING_CSK3_KEY_OFST + C_OTP_MAPPING_CSK3_KEY_SIZE )
/** CSK Signature - slot3 - 0x023c */
#define	C_OTP_MAPPING_CSK3_SIGN_OFST			C_OTP_MAPPING_CSK3_KEY_END_OFST
#define	C_OTP_MAPPING_CSK3_SIGN_SIZE			C_OTP_MAPPING_CSK_KEY_SIZE
#define	C_OTP_MAPPING_CSK3_SIGN_END_OFST		( C_OTP_MAPPING_CSK3_SIGN_OFST + C_OTP_MAPPING_CSK3_SIGN_SIZE )

#define	C_OTP_MAPPING_CSK_END_OFST				C_OTP_MAPPING_CSK3_SIGN_END_OFST

#define	C_OTP_MAPPING_LAST_CSK_OFST				( C_OTP_MAPPING_CSK_END_OFST - C_OTP_MAPPING_CSK_AERA_SIZE )
#define C_OTP_MAPPING_NB_CSK_SLOTS				( ( C_OTP_MAPPING_CSK_END_OFST - C_OTP_MAPPING_CSK_OFST ) / C_OTP_MAPPING_CSK_AERA_SIZE )

#define C_OTP_MAPPING_CSK_SLOT_MAX				( C_OTP_MAPPING_NB_CSK_SLOTS - 1 )

/** BOOT Address *************************************************************/
#define	C_OTP_MAPPING_BOOT_ADDR_AERA_OFST		C_OTP_MAPPING_CSK_END_OFST
#define	C_OTP_MAPPING_BOOT_ADDR_ELMNT_SIZE		sizeof(uintmax_t)

#define	C_OTP_MAPPING_BOOT_ADDR1_OFST			C_OTP_MAPPING_BOOT_ADDR_AERA_OFST
#define	C_OTP_MAPPING_BOOT_ADDR1_SIZE			C_OTP_MAPPING_BOOT_ADDR_ELMNT_SIZE
#define	C_OTP_MAPPING_BOOT_ADDR1_END_OFST		( C_OTP_MAPPING_BOOT_ADDR1_OFST + C_OTP_MAPPING_BOOT_ADDR1_SIZE )

#define	C_OTP_MAPPING_BOOT_ADDR2_OFST			C_OTP_MAPPING_BOOT_ADDR1_END_OFST
#define	C_OTP_MAPPING_BOOT_ADDR2_SIZE			C_OTP_MAPPING_BOOT_ADDR_ELMNT_SIZE
#define	C_OTP_MAPPING_BOOT_ADDR2_END_OFST		( C_OTP_MAPPING_BOOT_ADDR2_OFST + C_OTP_MAPPING_BOOT_ADDR2_SIZE )

#define	C_OTP_MAPPING_BOOT_ADDR3_OFST			C_OTP_MAPPING_BOOT_ADDR2_END_OFST
#define	C_OTP_MAPPING_BOOT_ADDR3_SIZE			C_OTP_MAPPING_BOOT_ADDR_ELMNT_SIZE
#define	C_OTP_MAPPING_BOOT_ADDR3_END_OFST		( C_OTP_MAPPING_BOOT_ADDR3_OFST + C_OTP_MAPPING_BOOT_ADDR3_SIZE )

#define	C_OTP_MAPPING_BOOT_ADDR_END_OFST		C_OTP_MAPPING_BOOT_ADDR3_END_OFST

#define	C_OTP_MAPPING_LAST_BOOT_ADDR_OFST		( C_OTP_MAPPING_BOOT_ADDR_END_OFST - C_OTP_MAPPING_BOOT_ADDR_ELMNT_SIZE )
#define C_OTP_MAPPING_NB_BOOT_ADDR_SLOTS		( ( C_OTP_MAPPING_BOOT_ADDR_END_OFST - C_OTP_MAPPING_BOOT_ADDR_AERA_OFST ) / C_OTP_MAPPING_BOOT_ADDR_ELMNT_SIZE )

#define C_OTP_MAPPING_BOOT_ADDR_SLOT_MAX		( C_OTP_MAPPING_NB_BOOT_ADDR_SLOTS - 1 )

/** Application's Reference Version *******************************************/
#define	C_OTP_MAPPING_APP_REFV_AREA_OFST		C_OTP_MAPPING_BOOT_ADDR_END_OFST
#define	C_OTP_MAPPING_APP_REFV_ELMNT_SIZE		sizeof(uint32_t)

#define	C_OTP_MAPPING_APP_REFV1_OFST			C_OTP_MAPPING_APP_REFV_AREA_OFST
#define	C_OTP_MAPPING_APP_REFV1_SIZE			C_OTP_MAPPING_APP_REFV_ELMNT_SIZE
#define	C_OTP_MAPPING_APP_REFV1_END_OFST		( C_OTP_MAPPING_APP_REFV1_OFST + C_OTP_MAPPING_APP_REFV1_SIZE )

#define	C_OTP_MAPPING_APP_REFV2_OFST			C_OTP_MAPPING_APP_REFV1_END_OFST
#define	C_OTP_MAPPING_APP_REFV2_SIZE			C_OTP_MAPPING_APP_REFV_ELMNT_SIZE
#define	C_OTP_MAPPING_APP_REFV2_END_OFST		( C_OTP_MAPPING_APP_REFV2_OFST + C_OTP_MAPPING_APP_REFV2_SIZE )

#define	C_OTP_MAPPING_APP_REFV3_OFST			C_OTP_MAPPING_APP_REFV2_END_OFST
#define	C_OTP_MAPPING_APP_REFV3_SIZE			C_OTP_MAPPING_APP_REFV_ELMNT_SIZE
#define	C_OTP_MAPPING_APP_REFV3_END_OFST		( C_OTP_MAPPING_APP_REFV3_OFST + C_OTP_MAPPING_APP_REFV3_SIZE )

#define	C_OTP_MAPPING_APP_REFV_END_OFST			C_OTP_MAPPING_APP_REFV3_END_OFST

#define	C_OTP_MAPPING_LAST_APP_REFV_OFST		( C_OTP_MAPPING_APP_REFV_END_OFST - C_OTP_MAPPING_APP_REFV_ELMNT_SIZE )
#define C_OTP_MAPPING_NB_APP_REFV_SLOTS			( ( C_OTP_MAPPING_APP_REFV_END_OFST - C_OTP_MAPPING_APP_REFV_AREA_OFST ) / C_OTP_MAPPING_APP_REFV_ELMNT_SIZE )

#define C_OTP_MAPPING_APP_REFV_SLOT_MAX			( C_OTP_MAPPING_NB_APP_REFV_SLOTS - 1 )






#define	C_OTP_RMA_MODE_PATTERN					0xa5a55a5a



/** Enumerations **************************************************************/

/** Structures ****************************************************************/

/** Functions *****************************************************************/

/** Macros ********************************************************************/

#endif /* _OTP_MAPPING_H_ */

/******************************************************************************/
/* End Of File */
